name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'test'
env:
  GH_USER: aqua-sb-bot
  RELEASE_VERSION: v0
  MAJOR_VERSION: v0.0
  MINOR_VERSION: v0.0.1
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create bundle
        run: make bundle
      - name: Login to Docker Container registry
        uses: docker/login-action@v3
        with:
#          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy policy bundle to docker.io (for backwards compatibility)
        run: |
          tags=(latest ${{ env.RELEASE_VERSION}} ${{env.MINOR_VERSION }} ${{ env.MAJOR_VERSION }})
          for tag in ${tags[@]}; do
              oras push docker.io/${{ vars.DOCKERHUB_USERNAME }}/trivy-policies:latest \
              --artifact-type application/vnd.cncf.openpolicyagent.config.v1+json \
              --annotation "org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
              --annotation "org.opencontainers.image.revision=$GITHUB_SHA" \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip
          done
      - name: Deploy checks bundle to docker.io
        run: |
          tags=(latest ${{ env.RELEASE_VERSION}} ${{env.MINOR_VERSION }} ${{ env.MAJOR_VERSION }})
          for tag in ${tags[@]}; do
              oras push docker.io/${{ github.repository }}:latest \
              --artifact-type application/vnd.cncf.openpolicyagent.config.v1+json \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip
          done
